import mongoose, { ClientSession, Types } from 'mongoose';
import { Bill, DiscountType, PaymentMethod } from '../models/Bill.js'; import { InvoiceCounter } from '../models/InvoiceCounter.js'; import { Client } from '../models/Client.js'; import { Service } from '../models/Service.js'; import { Employee } from '../models/Employee.js'; import { Product } from '../models/Product.js'; import { StockHistory } from '../models/StockHistory.js'; import { AppError } from '../utils/AppError.js'; import { calculateBillTotals } from './billing-calculation.service.js'; import { applyLoyalty, redemptionValue } from './loyalty.service.js';

export type BillRequest = { customerType: 'EXISTING_CLIENT' | 'WALK_IN'; clientId?: string; customerName?: string; customerMobile?: string; services: { serviceId: string; employeeId: string; quantity: number }[]; products: { productId: string; quantity: number }[]; discountType: DiscountType; discountValue: number; taxRate: number; loyaltyPointsRedeemed?: number; payments: { method: PaymentMethod; amount: number }[]; notes?: string; createdBy: string; };
const safeId = (value: string, label: string) => { if (!Types.ObjectId.isValid(value)) throw new AppError(400, `${label} is invalid`); return new Types.ObjectId(value); };
const round = (value: number) => Math.round((value + Number.EPSILON) * 100) / 100;
const invoiceNumber = async (session: ClientSession) => { const year = new Date().getFullYear(); const counter = await InvoiceCounter.findOneAndUpdate({ year }, { $inc: { sequence: 1 } }, { new: true, upsert: true, session, setDefaultsOnInsert: true }); return `INV-${year}-${String(counter.sequence).padStart(6, '0')}`; };
export const createBill = async (input: BillRequest) => { const session = await mongoose.startSession(); try { let created: any; await session.withTransaction(async () => { created = await createInTransaction(input, session); }); return toBill(created); } catch (error) { const message = error instanceof Error ? error.message : ''; if (/Transaction numbers are only allowed|does not support transactions|replica set/i.test(message)) throw new AppError(503, 'Billing requires MongoDB configured as a replica set because invoice creation is transactional'); throw error; } finally { await session.endSession(); } };
const createInTransaction = async (input: BillRequest, session: ClientSession) => {
  if (!input.services.length && !input.products.length) throw new AppError(400, 'Add at least one service or product');
  if (!Number.isFinite(input.discountValue) || input.discountValue < 0 || (input.discountType === 'PERCENTAGE' && input.discountValue > 100)) throw new AppError(400, 'Invalid discount');
  if (!Number.isFinite(input.taxRate) || input.taxRate < 0) throw new AppError(400, 'Invalid tax rate');
  let customerName = input.customerName?.trim() || ''; let customerMobile = input.customerMobile?.trim() || ''; let customerEmail = ''; let clientId: Types.ObjectId | null = null;
  if (input.customerType === 'EXISTING_CLIENT') { if (!input.clientId) throw new AppError(400, 'clientId is required for an existing client'); clientId = safeId(input.clientId, 'clientId'); const client = await Client.findOne({ _id: clientId, isActive: true }).session(session); if (!client) throw new AppError(404, 'Client not found or inactive'); customerName = `${client.firstName} ${client.lastName ?? ''}`.trim(); customerMobile = client.mobileNumber ?? ''; customerEmail = client.email ?? ''; } else if (input.customerType !== 'WALK_IN' || !customerName) throw new AppError(400, 'customerName is required for a walk-in customer');
  const serviceIds = input.services.map((line) => safeId(line.serviceId, 'serviceId')); const employeeIds = input.services.map((line) => safeId(line.employeeId, 'employeeId')); const productIds = input.products.map((line) => safeId(line.productId, 'productId'));
  const [services, employees, products] = await Promise.all([Service.find({ _id: { $in: serviceIds }, isActive: true }).session(session), Employee.find({ _id: { $in: employeeIds }, isActive: true }).session(session), Product.find({ _id: { $in: productIds }, isActive: true }).session(session)]);
  const servicesById = new Map(services.map((item) => [item.id, item])); const employeesById = new Map(employees.map((item) => [item.id, item])); const productsById = new Map(products.map((item) => [item.id, item]));
  const serviceLines = input.services.map((line) => { if (!Number.isInteger(line.quantity) || line.quantity <= 0) throw new AppError(400, 'Service quantity must be greater than zero'); const service = servicesById.get(line.serviceId); const employee = employeesById.get(line.employeeId); if (!service) throw new AppError(404, 'Service not found or inactive'); if (!employee) throw new AppError(404, 'Employee not found or inactive'); if (!employee.assignedServices.some((id) => id.equals(service._id))) throw new AppError(400, `${employee.firstName} ${employee.lastName} is not assigned to ${service.name}`); return { serviceId: service._id, serviceName: service.name, employeeId: employee._id, employeeName: `${employee.firstName} ${employee.lastName}`, duration: service.duration, unitPrice: service.price, quantity: line.quantity, total: round(service.price * line.quantity) }; });
  const requestedStock = new Map<string, number>(); input.products.forEach((line) => { if (!Number.isInteger(line.quantity) || line.quantity <= 0) throw new AppError(400, 'Product quantity must be greater than zero'); requestedStock.set(line.productId, (requestedStock.get(line.productId) ?? 0) + line.quantity); });
  const productLines = input.products.map((line) => { const product = productsById.get(line.productId); if (!product) throw new AppError(404, 'Product not found or inactive'); const required = requestedStock.get(line.productId) ?? 0; if (product.currentStock < required) throw new AppError(400, `Insufficient stock for ${product.name}`); return { productId: product._id, productName: product.name, sku: product.sku, unitPrice: product.sellingPrice, quantity: line.quantity, total: round(product.sellingPrice * line.quantity) }; });
  const baseTotals = calculateBillTotals(serviceLines, productLines, input.discountType, input.discountValue, input.taxRate);
  if (input.discountType === 'FIXED' && input.discountValue > baseTotals.subtotal) throw new AppError(400, 'Discount cannot exceed the subtotal');
  const loyaltyPointsRedeemed = input.loyaltyPointsRedeemed ?? 0;
  if (input.customerType !== 'EXISTING_CLIENT' && loyaltyPointsRedeemed) throw new AppError(400, 'Loyalty points can only be redeemed for an existing client');
  const loyaltyDiscountAmount = clientId ? await redemptionValue(clientId, loyaltyPointsRedeemed, baseTotals.taxableAmount, session) : 0;
  // Loyalty is an additional discount before GST. Keep the original discount amount
  // separately so both discounts remain auditable on the immutable invoice snapshot.
  const calculatedTotals = loyaltyDiscountAmount
    ? calculateBillTotals(serviceLines, productLines, 'FIXED', baseTotals.discountAmount + loyaltyDiscountAmount, input.taxRate)
    : baseTotals;
  const totals = { ...calculatedTotals, discountAmount: baseTotals.discountAmount };
  const paid = round(input.payments.reduce((sum, payment) => sum + payment.amount, 0)); if (input.payments.some((p) => !['CASH', 'UPI', 'CARD'].includes(p.method) || !Number.isFinite(p.amount) || p.amount <= 0)) throw new AppError(400, 'Each payment must use a valid method and amount greater than zero'); if (paid > totals.grandTotal) throw new AppError(400, 'Payment cannot be greater than grand total'); if (input.payments.length > 1 && paid !== totals.grandTotal) throw new AppError(400, 'Mixed payments must equal the grand total'); const paymentStatus = paid === totals.grandTotal ? 'PAID' : paid === 0 ? 'UNPAID' : 'PARTIALLY_PAID';
  const invoice = await invoiceNumber(session); const [bill] = await Bill.create([{ invoiceNumber: invoice, client: clientId, customerType: input.customerType, customerName, customerMobile, customerEmail, services: serviceLines, products: productLines, ...totals, discountType: input.discountType, discountValue: input.discountValue, loyaltyPointsRedeemed, loyaltyDiscountAmount, taxRate: input.taxRate, paymentStatus, payments: input.payments, paymentMethods: [...new Set(input.payments.map((p) => p.method))], notes: input.notes?.trim(), createdBy: safeId(input.createdBy, 'createdBy') }], { session });
  for (const [productId, quantity] of requestedStock) { const product = productsById.get(productId)!; const previousStock = product.currentStock; product.currentStock -= quantity; await product.save({ session }); await StockHistory.create([{ product: product._id, action: 'Sale', quantity: -quantity, previousStock, newStock: product.currentStock, remarks: `Sold on invoice ${invoice}`, invoiceNumber: invoice }], { session }); }
  if (clientId) {
    await Client.updateOne({ _id: clientId }, { $set: { lastVisitAt: new Date() }, $inc: { totalVisits: 1 } }, { session });
    // Eligible spend is the post-discount, pre-tax invoice amount. This keeps GST
    // out of points while preventing points from being earned on redeemed value.
    await applyLoyalty({ client: clientId, bill: bill._id, redeem: loyaltyPointsRedeemed, eligibleSpend: totals.taxableAmount, user: safeId(input.createdBy, 'createdBy') }, session);
  }
  return bill;
};
export const listBills = async (options: { page: number; limit: number; search?: string; from?: Date; to?: Date; paymentStatus?: string; sortBy: 'createdAt' | 'invoiceNumber' | 'grandTotal'; sortOrder: 'asc' | 'desc' }) => { const filter: Record<string, unknown> = {}; if (options.search) { const pattern = new RegExp(options.search.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i'); filter.$or = [{ invoiceNumber: pattern }, { customerName: pattern }, { customerMobile: pattern }]; } if (options.from || options.to) filter.createdAt = { ...(options.from ? { $gte: options.from } : {}), ...(options.to ? { $lte: options.to } : {}) }; if (options.paymentStatus) filter.paymentStatus = options.paymentStatus; const [bills, total] = await Promise.all([Bill.find(filter).sort({ [options.sortBy]: options.sortOrder === 'asc' ? 1 : -1 }).skip((options.page - 1) * options.limit).limit(options.limit), Bill.countDocuments(filter)]); return { bills: bills.map(toBill), pagination: { page: options.page, limit: options.limit, total, totalPages: Math.ceil(total / options.limit) } }; };
export const getBill = async (id: string) => { if (!Types.ObjectId.isValid(id)) throw new AppError(400, 'Invalid bill ID'); const bill = await Bill.findById(id).populate('createdBy', 'name email role'); if (!bill) throw new AppError(404, 'Bill not found'); return toBill(bill); };
const toBill = (bill: any) => ({ id: bill.id, invoiceNumber: bill.invoiceNumber, client: bill.client, customerType: bill.customerType, customerName: bill.customerName, customerMobile: bill.customerMobile, customerEmail: bill.customerEmail, services: bill.services, products: bill.products, subtotal: bill.subtotal, discountType: bill.discountType, discountValue: bill.discountValue, discountAmount: bill.discountAmount, loyaltyPointsRedeemed: bill.loyaltyPointsRedeemed, loyaltyDiscountAmount: bill.loyaltyDiscountAmount, taxableAmount: bill.taxableAmount, taxRate: bill.taxRate, taxAmount: bill.taxAmount, grandTotal: bill.grandTotal, paymentStatus: bill.paymentStatus, payments: bill.payments, paymentMethods: bill.paymentMethods, notes: bill.notes, createdBy: bill.createdBy, createdAt: bill.createdAt, updatedAt: bill.updatedAt });
