import { Bill } from '../models/Bill.js';
import { DateRange, indiaDateLabels, resolveIndiaDateRange } from '../utils/dateRange.js';

export const REPORT_TYPES = ['sales', 'services', 'products', 'employees', 'customers', 'tax'] as const;
export type ReportType = typeof REPORT_TYPES[number];
type Options = { from?: string; to?: string; page: number; limit: number; search?: string; };
const match = (range: DateRange) => ({ createdAt: { $gte: range.from, $lt: range.to } });
const n = (value: unknown) => Number(value ?? 0);
const customerFields = { customerKey: { $cond: [{ $ne: ['$client', null] }, { $concat: ['client:', { $toString: '$client' }] }, { $cond: [{ $ne: [{ $ifNull: ['$customerMobile', ''] }, ''] }, { $concat: ['mobile:', '$customerMobile'] }, { $concat: ['walk-in:', { $toString: '$_id' }] }] }] } };
const pagination = (page: number, limit: number, total: number) => ({ page, limit, total, totalPages: Math.ceil(total / limit) });
const pattern = (value?: string) => value ? new RegExp(value.replace(/[.*+?^${}()|[\]\\]/g, '\\$&'), 'i') : undefined;

export const getReport = async (type: ReportType, options: Options) => {
  const range = resolveIndiaDateRange(options.from, options.to); const search = pattern(options.search);
  if (type === 'sales' || type === 'tax') return salesOrTax(type, range);
  if (type === 'services') return groupedReport({ range, page: options.page, limit: options.limit, search, unwind: '$services', id: '$services.serviceId', name: '$services.serviceName', quantity: '$services.quantity', revenue: '$services.total' });
  if (type === 'products') return groupedReport({ range, page: options.page, limit: options.limit, search, unwind: '$products', id: '$products.productId', name: '$products.productName', sku: '$products.sku', quantity: '$products.quantity', revenue: '$products.total' });
  if (type === 'employees') return employeeReport(range, options.page, options.limit, search);
  return customerReport(range, options.page, options.limit, search);
};

const salesOrTax = async (type: 'sales' | 'tax', range: DateRange) => {
  const [data] = await Bill.aggregate([{ $match: match(range) }, { $addFields: { serviceRevenue: { $sum: { $map: { input: '$services', as: 'line', in: '$$line.total' } } }, productRevenue: { $sum: { $map: { input: '$products', as: 'line', in: '$$line.total' } } }, paymentCount: { $size: '$payments' } } }, { $facet: { summary: [{ $group: { _id: null, revenue: { $sum: '$grandTotal' }, bills: { $sum: 1 }, discounts: { $sum: '$discountAmount' }, tax: { $sum: '$taxAmount' }, taxableSales: { $sum: '$taxableAmount' }, grossSales: { $sum: '$subtotal' }, serviceRevenue: { $sum: '$serviceRevenue' }, productRevenue: { $sum: '$productRevenue' } } }, { $project: { _id: 0, revenue: 1, bills: 1, discounts: 1, tax: 1, taxableSales: 1, grossSales: 1, serviceRevenue: 1, productRevenue: 1, averageBillValue: { $cond: [{ $gt: ['$bills', 0] }, { $divide: ['$revenue', '$bills'] }, 0] } } }], daily: [{ $group: { _id: { $dateToString: { date: '$createdAt', format: '%Y-%m-%d', timezone: 'Asia/Kolkata' } }, bills: { $sum: 1 }, revenue: { $sum: '$grandTotal' }, tax: { $sum: '$taxAmount' }, discounts: { $sum: '$discountAmount' }, taxableSales: { $sum: '$taxableAmount' }, grossSales: { $sum: '$subtotal' } } }, { $sort: { _id: 1 } }, { $project: { _id: 0, date: '$_id', bills: 1, revenue: 1, tax: 1, discounts: 1, taxableSales: 1, grossSales: 1, averageBillValue: { $cond: [{ $gt: ['$bills', 0] }, { $divide: ['$revenue', '$bills'] }, 0] } } }], payments: [{ $unwind: '$payments' }, { $group: { _id: { $cond: [{ $gt: ['$paymentCount', 1] }, 'MIXED', '$payments.method'] }, amount: { $sum: '$payments.amount' }, bills: { $addToSet: '$_id' } } }, { $project: { _id: 0, method: '$_id', amount: 1, bills: { $size: '$bills' } } }] } }]).allowDiskUse(true);
  const summary = data?.summary?.[0] ?? {}; const dailyByDate = new Map<string, any>((data?.daily ?? []).map((item: any): [string, any] => [item.date, item])); const daily: any[] = indiaDateLabels(range).map((date) => dailyByDate.get(date) ?? { date, bills: 0, revenue: 0, tax: 0, discounts: 0, taxableSales: 0, grossSales: 0, averageBillValue: 0 }); const paymentTotal = (data?.payments ?? []).reduce((sum: number, item: any) => sum + n(item.amount), 0);
  return { range: { from: range.fromDate, to: range.toDate }, summary: { revenue: n(summary.revenue), bills: n(summary.bills), averageBillValue: n(summary.averageBillValue), discounts: n(summary.discounts), tax: n(summary.tax), taxableSales: n(summary.taxableSales), grossSales: n(summary.grossSales), serviceRevenue: n(summary.serviceRevenue), productRevenue: n(summary.productRevenue) }, rows: type === 'sales' ? daily : daily.map((item) => ({ date: item.date, grossSales: n(item.grossSales), discounts: n(item.discounts), taxableSales: n(item.taxableSales), tax: n(item.tax), revenue: n(item.revenue) })), paymentMethods: ['CASH', 'UPI', 'CARD', 'MIXED'].map((method) => { const item = (data?.payments ?? []).find((value: any) => value.method === method); const amount = n(item?.amount); return { method, amount, bills: n(item?.bills), percentage: paymentTotal ? Math.round(amount / paymentTotal * 10000) / 100 : 0 }; }) };
};

const groupedReport = async (input: { range: DateRange; page: number; limit: number; search?: RegExp; unwind: string; id: string; name: string; sku?: string; quantity: string; revenue: string; }) => {
  const group: Record<string, unknown> = { _id: input.id, name: { $first: input.name }, quantity: { $sum: input.quantity }, revenue: { $sum: input.revenue } };
  if (input.sku) group.sku = { $first: input.sku };
  const pipeline: any[] = [{ $match: match(input.range) }, { $unwind: input.unwind }, { $group: group }, { $project: { _id: 0, id: { $toString: '$_id' }, name: 1, sku: 1, quantity: 1, revenue: 1 } }];
  if (input.search) pipeline.push({ $match: { $or: [{ name: input.search }, { sku: input.search }] } });
  pipeline.push({ $sort: { revenue: -1, quantity: -1, name: 1 } }, { $facet: { rows: [{ $skip: (input.page - 1) * input.limit }, { $limit: input.limit }], total: [{ $count: 'value' }], totals: [{ $group: { _id: null, revenue: { $sum: '$revenue' }, quantity: { $sum: '$quantity' } } }] } });
  const [data] = await Bill.aggregate(pipeline).allowDiskUse(true); const total = n(data?.total?.[0]?.value); const totalRevenue = n(data?.totals?.[0]?.revenue); return { range: { from: input.range.fromDate, to: input.range.toDate }, summary: { totalRevenue, totalQuantity: n(data?.totals?.[0]?.quantity) }, rows: (data?.rows ?? []).map((row: any) => ({ ...row, percentage: totalRevenue ? Math.round(n(row.revenue) / totalRevenue * 10000) / 100 : 0 })), pagination: pagination(input.page, input.limit, total) };
};

const employeeReport = async (range: DateRange, page: number, limit: number, search?: RegExp) => { const pipeline: any[] = [{ $match: match(range) }, { $addFields: customerFields }, { $unwind: '$services' }, { $group: { _id: '$services.employeeId', name: { $first: '$services.employeeName' }, servicesPerformed: { $sum: '$services.quantity' }, revenue: { $sum: '$services.total' }, customers: { $addToSet: '$customerKey' } } }, { $project: { _id: 0, id: { $toString: '$_id' }, name: 1, servicesPerformed: 1, revenue: 1, customersServed: { $size: '$customers' } } }]; if (search) pipeline.push({ $match: { name: search } }); pipeline.push({ $sort: { revenue: -1, servicesPerformed: -1, name: 1 } }, { $facet: { rows: [{ $skip: (page - 1) * limit }, { $limit: limit }], total: [{ $count: 'value' }], totals: [{ $group: { _id: null, revenue: { $sum: '$revenue' }, servicesPerformed: { $sum: '$servicesPerformed' } } }] } }); const [data] = await Bill.aggregate(pipeline).allowDiskUse(true); const totalRevenue = n(data?.totals?.[0]?.revenue); return { range: { from: range.fromDate, to: range.toDate }, summary: { totalRevenue, servicesPerformed: n(data?.totals?.[0]?.servicesPerformed) }, rows: (data?.rows ?? []).map((row: any) => ({ ...row, percentage: totalRevenue ? Math.round(n(row.revenue) / totalRevenue * 10000) / 100 : 0 })), pagination: pagination(page, limit, n(data?.total?.[0]?.value)) };
};

const customerReport = async (range: DateRange, page: number, limit: number, search?: RegExp) => {
  const pipeline: any[] = [
    { $match: match(range) }, { $addFields: customerFields },
    { $group: { _id: '$customerKey', name: { $first: '$customerName' }, client: { $first: '$client' }, bills: { $sum: 1 }, spend: { $sum: '$grandTotal' } } },
    { $project: { _id: 0, id: { $cond: [{ $ne: ['$client', null] }, { $toString: '$client' }, null] }, name: 1, bills: 1, spend: 1 } },
  ];
  if (search) pipeline.push({ $match: { name: search } });
  pipeline.push({ $sort: { spend: -1, bills: -1, name: 1 } }, { $facet: { rows: [{ $skip: (page - 1) * limit }, { $limit: limit }], total: [{ $count: 'value' }], totals: [{ $group: { _id: null, customers: { $sum: 1 }, revenue: { $sum: '$spend' }, returningCustomers: { $sum: { $cond: [{ $gt: ['$bills', 1] }, 1, 0] } } } }] } });
  const [data] = await Bill.aggregate(pipeline).allowDiskUse(true); const summary = data?.totals?.[0] ?? {}; const customers = n(summary.customers);
  return { range: { from: range.fromDate, to: range.toDate }, summary: { uniqueCustomers: customers, returningCustomers: n(summary.returningCustomers), totalRevenue: n(summary.revenue), averageCustomerSpend: customers ? n(summary.revenue) / customers : 0 }, rows: data?.rows ?? [], pagination: pagination(page, limit, n(data?.total?.[0]?.value)) };
};

export const reportCsv = (type: ReportType, report: any): string => { const headers = type === 'sales' ? ['Date', 'Bills', 'Revenue', 'Average Bill'] : type === 'tax' ? ['Date', 'Gross Sales', 'Discounts', 'Taxable Sales', 'GST', 'Net Sales'] : type === 'services' ? ['Service', 'Performed', 'Revenue', 'Revenue %'] : type === 'products' ? ['Product', 'SKU', 'Quantity Sold', 'Revenue', 'Revenue %'] : type === 'employees' ? ['Employee', 'Services Performed', 'Revenue', 'Customers Served', 'Revenue %'] : ['Customer', 'Bills', 'Spend']; const values = report.rows.map((row: any) => type === 'sales' ? [row.date, row.bills, row.revenue, row.averageBillValue] : type === 'tax' ? [row.date, row.grossSales, row.discounts, row.taxableSales, row.tax, row.revenue] : type === 'services' ? [row.name, row.quantity, row.revenue, row.percentage] : type === 'products' ? [row.name, row.sku ?? '', row.quantity, row.revenue, row.percentage] : type === 'employees' ? [row.name, row.servicesPerformed, row.revenue, row.customersServed, row.percentage] : [row.name, row.bills, row.spend]); return [headers, ...values].map((row) => row.map((value: unknown) => `"${String(value ?? '').replace(/"/g, '""')}"`).join(',')).join('\n'); };
