import { Schema, Types, model } from 'mongoose';

export type CustomerType = 'EXISTING_CLIENT' | 'WALK_IN';
export type DiscountType = 'FIXED' | 'PERCENTAGE';
export type PaymentMethod = 'CASH' | 'UPI' | 'CARD';
export type PaymentStatus = 'PAID' | 'PARTIALLY_PAID' | 'UNPAID';

const serviceLineSchema = new Schema({ serviceId: { type: Types.ObjectId, ref: 'Service', required: true }, serviceName: { type: String, required: true }, employeeId: { type: Types.ObjectId, ref: 'Employee', required: true }, employeeName: { type: String, required: true }, duration: { type: Number, required: true }, unitPrice: { type: Number, required: true }, quantity: { type: Number, required: true }, total: { type: Number, required: true } }, { _id: false });
const productLineSchema = new Schema({ productId: { type: Types.ObjectId, ref: 'Product', required: true }, productName: { type: String, required: true }, sku: String, unitPrice: { type: Number, required: true }, quantity: { type: Number, required: true }, total: { type: Number, required: true } }, { _id: false });
const paymentSchema = new Schema({ method: { type: String, enum: ['CASH', 'UPI', 'CARD'], required: true }, amount: { type: Number, required: true, min: 0.01 } }, { _id: false });
const billSchema = new Schema({ invoiceNumber: { type: String, required: true, unique: true }, client: { type: Types.ObjectId, ref: 'Client', default: null }, customerType: { type: String, enum: ['EXISTING_CLIENT', 'WALK_IN'], required: true }, customerName: { type: String, required: true }, customerMobile: String, customerEmail: String, services: { type: [serviceLineSchema], default: [] }, products: { type: [productLineSchema], default: [] }, subtotal: { type: Number, required: true }, discountType: { type: String, enum: ['FIXED', 'PERCENTAGE'], default: 'FIXED' }, discountValue: { type: Number, default: 0 }, discountAmount: { type: Number, default: 0 }, taxableAmount: { type: Number, required: true }, taxRate: { type: Number, default: 0 }, taxAmount: { type: Number, default: 0 }, grandTotal: { type: Number, required: true }, paymentStatus: { type: String, enum: ['PAID', 'PARTIALLY_PAID', 'UNPAID'], required: true }, payments: { type: [paymentSchema], default: [] }, paymentMethods: { type: [String], enum: ['CASH', 'UPI', 'CARD'], default: [] }, notes: { type: String, trim: true, maxlength: 2000 }, createdBy: { type: Types.ObjectId, ref: 'User', required: true } }, { timestamps: true });
export const Bill = model('Bill', billSchema);
