import cors from 'cors';
import cookieParser from 'cookie-parser';
import express from 'express';
import { createRequire } from 'node:module';
import morgan from 'morgan';
import { env } from './config/env.js';
import { errorHandler, notFound } from './middleware/error.middleware.js';
import { authRouter } from './routes/auth.routes.js';
import { clientRouter } from './routes/client.routes.js';
import { serviceRouter } from './routes/service.routes.js';
import { productRouter } from './routes/product.routes.js';
import { employeeRouter } from './routes/employee.routes.js';
import { billRouter } from './routes/bill.routes.js';
import { dashboardRouter } from './routes/dashboard.routes.js';
import { reportRouter } from './routes/report.routes.js';
import { insightRouter } from './routes/insight.routes.js';
import { actionCenterRouter } from './routes/actionCenter.routes.js';
import { loyaltyRouter } from './routes/loyalty.routes.js';

const require = createRequire(import.meta.url);
const helmet = require('helmet') as typeof import('helmet').default;

export const app = express();
app.use(helmet());
app.use(cors({ origin: env.clientUrl, credentials: true }));
app.use(cookieParser());
app.use(express.json({ limit: '10kb' }));
app.use(morgan(env.nodeEnv === 'production' ? 'combined' : 'dev'));
app.get('/api/health', (_req, res) => res.json({ status: 'ok' }));
app.use('/api/auth', authRouter);
app.use('/api/clients', clientRouter);
app.use('/api/services', serviceRouter);
app.use('/api/products', productRouter);
app.use('/api/employees', employeeRouter);
app.use('/api/bills', billRouter);
app.use('/api/dashboard', dashboardRouter);
app.use('/api/reports', reportRouter);
app.use('/api/insights', insightRouter);
app.use('/api/action-center', actionCenterRouter);
app.use('/api/loyalty', loyaltyRouter);
app.use(notFound);
app.use(errorHandler);
